name: flutter_eassypharmacy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  dio: ^5.4.0
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  logger: ^2.0.2+1
  flutter_svg: ^2.0.9
#  carousel_slider: ^4.2.1
  # file_picker: ^6.1.1
  # image_picker: ^1.0.7
  # lazy_load_scrollview: ^1.3.0
  # pin_code_fields: ^8.0.1
  # dropdown_search: ^5.0.6
  # package_info_plus: ^5.0.1
  shimmer: ^3.0.0
  # fluttertoast: ^8.2.4
  # firebase_messaging: ^14.7.14
  # firebase_core: ^2.25.3
  # flutter_local_notifications: ^16.3.2
  # rxdart: ^0.27.7
  # url_launcher: ^6.2.4
#  webview_flutter: ^4.5.0
  cached_network_image: ^3.3.1
  # path_provider: ^2.1.2
  # permission_handler: ^11.2.0
  #  downloads_path_provider_28: ^0.1.2
  # flutter_launcher_icons: ^0.13.1
  # firebase_auth: ^4.17.3
  # country_code_picker: ^3.0.0
  # country_picker: ^2.0.24
  # recaptcha_enterprise_flutter: ^18.4.1
  # flutter_webview_pro: ^3.0.1+4
  # curved_progress_bar: ^1.0.2
  # syncfusion_flutter_datepicker:
  #   path: ./syncfusion_flutter_datepicker-24.2.3/
  syncfusion_flutter_datepicker: ^24.2.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # animated_bottom_navigation_bar: ^1.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/json/
