name: flutter_eassypharmacy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  dio: ^5.4.0
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  logger: ^2.0.2+1
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  syncfusion_flutter_datepicker: ^24.2.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # animated_bottom_navigation_bar: ^1.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/eassypharmacy_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
